language: objective-c
osx_image: xcode9
podfile: Podfile
before_install:
    - gem install cocoapods
    - gem install xcpretty -N
    - pod repo update
script:
    travis_retry xcodebuild build-for-testing -workspace LocalNotifications_Over_iOS10.xcworkspace -scheme LocalNotifications_Over_iOS10 -destination \"platform=iOS Simulator,name=iPhone 7,OS=11.0\" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
